In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vaish\onedrive\desktop\udempy_course_ai\python\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vaish\onedrive\desktop\udempy_course_ai\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\vaish\onedrive\desktop\udempy_course_ai\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.8 MB 16.1 MB/s eta 0:00:01
   ------ --------------------------------- 1.6/9.8 MB 6.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 3.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.8 MB 3.4 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.8 MB 2.9 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.8 MB 2.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.8 MB 2.2 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.8 MB 2.2 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.8 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.8 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.6 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.6 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.6 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 1.6 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.2 MB/s eta 0:00:05
   ----------------- ---------------------- 4.2/9.8 MB 943.7 kB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.8 MB 943.7 kB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.8 MB 943.7 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.8 MB 868.4 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.8 MB 868.4 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 849.2 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.8 MB 849.2 kB/s eta 0:00:07
   -------------------- ------------------- 5.0/9.8 MB 829.4 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.8 MB 829.4 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.8 MB 824.9 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.8 MB 829.6 kB/s eta 0:00:06
   ----------------------- ---------------- 5.8/9.8 MB 840.4 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.8 MB 840.4 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 844.7 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 847.6 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.8 MB 847.6 kB/s eta 0:00:05
   -------------------------- ------------- 6.6/9.8 MB 828.2 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.8 MB 828.2 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.8 MB 823.7 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.8 MB 823.7 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.8 MB 810.9 kB/s eta 0:00:04
   ----------------------------- ---------- 7.3/9.8 MB 820.5 kB/s eta 0:00:04
   ------------------------------ --------- 7.6/9.8 MB 830.0 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.8 MB 836.2 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.8 MB 845.5 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.8 MB 845.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.8 MB 839.5 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 839.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.8 MB 835.4 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.8 MB 835.4 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.8 MB 820.6 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.8 MB 820.6 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.8 MB 818.3 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 818.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 806.4 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 806.4 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 806.4 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 788.3 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 784.6 kB/s  0:00:12
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [6]:
data = [1,2,3,4,5,6]
series = pd.Series(data)
print("Series : \n",series)
print(type(series))

Series :
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>

In [8]:
# Create series from dictionary
dict = {'a':1,'b':2,'c':3,'d':4}
series = pd.Series(dict)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
data = [10,20,30]
index = ['a','b','c']
series = pd.Series(data,index = index)
print(series)

a    10
b    20
c    30
dtype: int64

In [5]:
data = {
    'Name':["Monica","Ross","Rach"],
    'City':["Banglore","NewYork","America"],
    'Age':[28,26,28]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name      City  Age
0  Monica  Banglore   28
1    Ross   NewYork   26
2    Rach   America   28
<class 'pandas.DataFrame'>

In [6]:
import numpy as np
np.array(df)

array([['Monica', 'Banglore', 28],
       ['Ross', 'NewYork', 26],
       ['Rach', 'America', 28]], dtype=object)

In [13]:
# Create a dataFame from list of Dictionaries

data = [
    {'Name':"Monica",'City':"America",'Age':28},
    {'Name':"Ross",'City':"New York",'Age':30},
    {'Name':"Rach",'City':"Germany",'Age':28},
    {'Name':"Phebe",'City':"London",'Age':31},
    {'Name':"Joey",'City':"India",'Age':29},
    {'Name':"Chandler",'City':"America",'Age':28}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

       Name      City  Age
0    Monica   America   28
1      Ross  New York   30
2      Rach   Germany   28
3     Phebe    London   31
4      Joey     India   29
5  Chandler   America   28
<class 'pandas.DataFrame'>

In [15]:
df = pd.read_csv('Pandas_DataFrame_Practice.csv')

In [16]:
df.head()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Midterm_Marks,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status
0,STU1001,Aditya,23,Male,Delhi,Mechanical,6,No,71.9,1.0,...,49,90,60,94,53.0,7.3,6.9,141932,B,Irregular
1,STU1002,Varun,23,Male,Mumbai,Mechanical,7,No,74.4,5.1,...,83,88,81,79,44.0,7.2,3.4,150038,B+,Irregular
2,STU1003,Vivaan,21,Female,Chennai,Mechanical,5,No,55.6,1.2,...,94,43,89,28,NaN,5.7,7.3,89457,B,Irregular
3,STU1004,Aryan,21,Female,Ahmedabad,AI & DS,4,No,74.1,6.1,...,88,33,93,82,47.0,7.1,6.2,159789,B,Irregular
4,STU1005,Harsh,22,Male,Haridwar,CSE,8,Yes,69.6,2.4,...,87,53,65,79,70.0,8.2,7.7,83986,B+,Irregular

In [17]:
df.tail()

,Student_ID,Name,Age,Gender,City,Department,Semester,Hostel,Attendance_%,Study_Hours_Daily,...,Midterm_Marks,Final_Exam_Marks,Project_Marks,Coding_Score,Communication_Score,Sleep_Hours,Screen_Time_Hours,Annual_Fees,Grade,Attendance_Status
248,STU1249,Mohit,21,Female,Ahmedabad,IT,5,Yes,59.2,2.7,...,42,83,100,57,77.0,6.4,3.0,146234,B+,Irregular
249,STU1250,Simran,23,Male,Kolkata,ECE,1,No,71.2,3.2,...,88,59,99,67,64.0,6.8,2.0,116287,B+,Irregular
250,STU1011,Aryan,23,Female,Chennai,Mechanical,7,Yes,67.5,3.6,...,35,48,41,72,73.0,8.1,5.8,176081,C,Irregular
251,STU1051,Aarav,23,Female,Kolkata,ECE,5,Yes,82.5,4.8,...,98,67,76,30,32.0,7.6,2.7,71342,B,Regular
252,STU1101,Aarav,21,Female,Pune,Civil,7,Yes,81.7,2.6,...,51,57,41,54,34.0,6.5,4.6,141260,D,Regular

In [18]:
## Accessing Data from Data Frame
data

[{'Name': 'Monica', 'City': 'America', 'Age': 28},
 {'Name': 'Ross', 'City': 'New York', 'Age': 30},
 {'Name': 'Rach', 'City': 'Germany', 'Age': 28},
 {'Name': 'Phebe', 'City': 'London', 'Age': 31},
 {'Name': 'Joey', 'City': 'India', 'Age': 29},
 {'Name': 'Chandler', 'City': 'America', 'Age': 28}]

In [20]:
df = data

In [21]:
df

[{'Name': 'Monica', 'City': 'America', 'Age': 28},
 {'Name': 'Ross', 'City': 'New York', 'Age': 30},
 {'Name': 'Rach', 'City': 'Germany', 'Age': 28},
 {'Name': 'Phebe', 'City': 'London', 'Age': 31},
 {'Name': 'Joey', 'City': 'India', 'Age': 29},
 {'Name': 'Chandler', 'City': 'America', 'Age': 28}]

In [23]:
df = pd.DataFrame(data)

In [24]:
df

       Name      City  Age
0    Monica   America   28
1      Ross  New York   30
2      Rach   Germany   28
3     Phebe    London   31
4      Joey     India   29
5  Chandler   America   28

In [25]:
df['Name']

0      Monica
1        Ross
2        Rach
3       Phebe
4        Joey
5    Chandler
Name: Name, dtype: str

In [28]:
type(df['Name'])

pandas.Series

In [ ]:
df.loc[0][0]

Name     Monica
City    America
Age          28
Name: 0, dtype: object

In [30]:
df.iloc[0]

Name     Monica
City    America
Age          28
Name: 0, dtype: object

In [7]:
df

     Name      City  Age
0  Monica  Banglore   28
1    Ross   NewYork   26
2    Rach   America   28

In [8]:
df["Name"]

0    Monica
1      Ross
2      Rach
Name: Name, dtype: str

In [12]:
df.at[1,"Name"]

'Ross'

In [16]:
df.iat[0,1]

'Banglore'

In [19]:
print(df.iat[2,2])

28

In [ ]:
## Data Manipulation

In [29]:
## Adding Column
df['Salary'] = [1000000,20000,5000]

In [22]:
df

     Name      City  Age   Salary
0  Monica  Banglore   28  1000000
1    Ross   NewYork   26    20000
2    Rach   America   28     5000

In [30]:
## Remove an column
df.drop('Salary',axis=1)

     Name      City  Age
0  Monica  Banglore   28
1    Ross   NewYork   26
2    Rach   America   28

In [35]:
df

     Name      City  Age   Salary
0  Monica  Banglore   28  1000000
1    Ross   NewYork   26    20000
2    Rach   America   28     5000

In [37]:
df.drop('Salary',axis=1,inplace=True)

In [38]:
df

     Name      City  Age
0  Monica  Banglore   28
1    Ross   NewYork   26
2    Rach   America   28

In [39]:
df['Age'] = df['Age']+1

In [40]:
df

     Name      City  Age
0  Monica  Banglore   29
1    Ross   NewYork   27
2    Rach   America   29

In [41]:
df.describe()

             Age
count   3.000000
mean   28.333333
std     1.154701
min    27.000000
25%    28.000000
50%    29.000000
75%    29.000000
max    29.000000

In [43]:
df.dtypes

Name      str
City      str
Age     int64
dtype: object