In [2]:
import pandas as pd
from io import StringIO

In [3]:
Data = '{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr. Developer"}]}'

In [4]:
df = pd.read_json(StringIO(Data))

In [5]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [6]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [7]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [8]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv?utm_source=chatgpt.com')

In [10]:
df.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
df.to_csv('https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv?utm_source=chatgpt.com')

In [12]:
url = 'https://html.spec.whatwg.org/multipage/?utm_source=chatgpt.com'

In [ ]:
# !pip install lxml
# !pip install html5lib
# !pip install beautifulsoup4

Collecting lxml
  Downloading lxml-6.1.2-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 2.8 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/4.0 MB 2.8 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.0 MB 3.0 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 3.3 MB/s  0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.2

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\vaish\onedrive\desktop\udempy_course_ai\python\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.6.1-py3-none-any.whl.metadata (3.4 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.6.1-py3-none-any.whl (8.7 kB)
Installing collected packages: webencodings, html5lib

   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.6.1

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.9.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\vaish\onedrive\desktop\udempy_course_ai\python\venv\lib\site-packages (from beautifulsoup4) (4.16.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading soupsieve-2.9.2-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4

   ---------------------------------------- 0/2 [soupsieve]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.15.0 soupsieve-2.9.2

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
url = 'https://www.w3schools.com/html/html_table_sizes.asp'

In [32]:
url = "https://gist.githubusercontent.com/hasankadirdemircan/889c14cb5f650dad49af45dedf977a1d/raw/table.html"

In [33]:
df = pd.read_html(url)

In [34]:
df

[                        Company           Contact  Country
 0           Alfreds Futterkiste      Maria Anders  Germany
 1    Centro comercial Moctezuma   Francisco Chang   Mexico
 2                  Ernst Handel     Roland Mendel  Austria
 3                Island Trading     Helen Bennett       UK
 4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
 5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy]

In [35]:
df[0]

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [ ]:
# !pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
pd.read_excel('short_student_data.xlsx')

    Name  Age Course  Marks
0   Aman   20    CSE     85
1  Priya   21    CSE     92
2  Rahul   20    ECE     78
3   Neha   21     IT     88
4   Riya   20    CSE     95

In [ ]:
df_excel = pd.read_excel('short_student_data.xlsx')

In [53]:
df.to_pickle('df_excel')

In [54]:
pd.read_pickle('df_excel')

    Name  Age Course  Marks
0   Aman   20    CSE     85
1  Priya   21    CSE     92
2  Rahul   20    ECE     78
3   Neha   21     IT     88
4   Riya   20    CSE     95